# .github/workflows/deploy.yml
name: GitHub Pages Deploy

on:
  push:
    branches:
      - main  # Substitua pelo branch correto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Executar o script de substituição
        env:
          SECRET_VALUE: ${{ secrets.PROFILE_NAME }}
          VARIABLE_VALUE: ${{ vars.PROFILE_NAME }}
        run: node replace.js

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Publica o diretório atual com o index.html modificado
