# .github/workflows/deploy.yml
name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Ou o branch principal do seu repositório

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Replace secret in script.js
        run: |
          SECRET_VALUE="${{ secrets.PROFILE_NAME }}"
          sed -i "s|{{SECRET_VALUE}}|$SECRET_VALUE|g" script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Diretorio a ser publicado no GitHub Pages
