# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

#Allow repo secrets
env:
  VITE_PROFILE_NAME_SECRET: ${{ secrets.PROFILE_NAME }}
  VITE_PROFILE_DESCRIPTION_VARIABLE: ${{ vars.PROFILE_DESCRIPTION }}
  VITE_TITLE_SECRET: ${{ vars.VITE_TITLE_SECRET }}
  VITE_PROFILE_DESCRIPTION_VARIABLE: ${{ vars.VITE_PROFILE_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_PACKAGE_SECRET: ${{ vars.VITE_BUY_A_PACKAGE_SECRET }}
  VITE_BUY_A_PACKAGE_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_PACKAGE_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_IMAGE_SECRET: ${{ vars.VITE_BUY_A_IMAGE_SECRET }}
  VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_IMAGE_DESCRIPTION_VARIABLE }}
  VITE_BUY_A_COURSE_SECRET: ${{ vars.VITE_BUY_A_COURSE_SECRET }}
  VITE_BUY_A_COURSE_DESCRIPTION_VARIABLE: ${{ vars.VITE_BUY_A_COURSE_DESCRIPTION_VARIABLE }}
  VITE_SPONSORSHIP_CONTACT_SECRET: ${{ vars.VITE_SPONSORSHIP_CONTACT_SECRET }}
  VITE_SPONSORSHIP_CONTACT_DESCRIPTION_VARIABLE: ${{ vars.VITE_SPONSORSHIP_CONTACT_DESCRIPTION_VARIABLE }}
  VITE_INSTAGRAM_SECRET: ${{ vars.VITE_INSTAGRAM_SECRET }}
  VITE_FACEBOOK_SECRET: ${{ vars.VITE_FACEBOOK_SECRET }}
  VITE_TIKTOK_SECRET: ${{ vars.VITE_TIKTOK_SECRET }}
  VITE_TELEGRAM_SECRET: ${{ vars.VITE_TELEGRAM_SECRET }}
  VITE_HOTMART_COURSE_SECRET: ${{ vars.VITE_HOTMART_COURSE_SECRET }}

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
